version: "3.7"
services:
  # Define the Mongo Express container and its properties
  mongo-express:
    image: hub.docker.target.com/mongo-express
    # Mongo express will be published to our host computer
    ports:
      - 8081:8081
    # We will define a network that all containers will join, this network will allow for referencing by name and ensure
    # that this environment is isolated from other docker networks on our host machine
    networks:
      - mongo-express-network
    # Since the mongo express server isn't much good without a running mongo instance, we will specify that the mongo
    # server should have successfully started prior to this container
    depends_on:
      - mongo-database
    # We specify all of the configuration for this container
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=myAdminUser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=myAdminPassword
      - ME_CONFIG_MONGODB_AUTH_DATABASE=my_db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=myAdminUser
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=myAdminPassword
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongo-database

  # Define the Mongo Database container
  # Note that image does not specify published port, it will still be accessible to other containers in the same
  # network, but not from our host machine.
  mongo-database:
    image: hub.docker.target.com/mongo
    # Connect to the same network as the mongo express service
    networks:
      - mongo-express-network
    # Specify a docker native volume to hold data
    volumes:  
      - mongo-express-db:/data/db
    # Specify all configration for this container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myAdminUser
      - MONGO_INITDB_ROOT_PASSWORD=myAdminPassword
      - MONGO_INITDB_DATABASE=my_db
    
# Define a shared network for this enviroment and use all default options
networks:
  mongo-express-network:

# Define the docker native volume for the mongo database and use all default optionss
volumes:
  mongo-express-db: